name: Publish Vue3 UI NPM package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Publish Vue3 UI NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm clean-install

      - name: Build for Production
        run: npm run build

      - name: Publish to NPM registry
        run: npm publish
